### ISSUE TITLE
Color circle/box with boolean parameter is not working

### ISSUE THREAD

**Issue by manuelmitasch** [manuelmitasch/chataigne-web-dashboard#3]

**Comment by glennsky** [comment]
Here's a little test .noisette to check functionality... 
[color_square_boolean_test.zip](https://github.com/manuelmitasch/chataigne-web-dashboard/files/8758723/color_square_boolean_test.zip)

there is also an issue with the Integer + Boolean not being transparent around the circle/square - as seen here:
![image](https://user-images.githubusercontent.com/636694/169926183-e66bd1a1-e52c-499d-a123-d8190c6ea265.png)

![image](https://user-images.githubusercontent.com/636694/169926370-5c896dcb-5553-449b-acdb-cabcbb16e4eb.png)

**Comment by manuelmitasch** [comment]
Fixed with https://github.com/manuelmitasch/chataigne-web-dashboard/commit/6897bfee4778986ec41cf86789fb3ee3c807183a
